import imagen1 from "../../assets/images/products/imagen10.jpg";
import imagen2 from "../../assets/images/products/imagen5.jpg";
import imagen3 from "../../assets/images/products/imagen12.jpg";
import imagen4 from "../../assets/images/products/imagen13.jpg";
import imagen5 from "../../assets/images/products/imagen14.jpg";
import imagen6 from "../../assets/images/products/imagen16.jpg";
import imagen7 from "../../assets/images/products/imagen17.jpg";
import imagen8 from "../../assets/images/products/imagen7.jpg";
import imagen9 from "../../assets/images/products/imagen19.jpg";
import imagen10 from "../../assets/images/products/imagen6.jpg";

const images = {
  imagen1,
  imagen2,
  imagen3,
  imagen4,
  imagen5,
  imagen6,
  imagen7,
  imagen8,
  imagen9,
  imagen10,
};

const productsPopularData = [
  {
    id: 15,
    slug: "mesa-popular-1",
    nombre: "Mesa popular 1",
    descripcion: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio ullam, quod laborum deserunt pla",
    categoria: "Moda",
    marca: "Marca A",
    precio: 100,
    rating: 4.5,
    stock: 10,
    imagen: images.imagen1,
  },
  {
    id: 16,
    slug: "producto-popular-2",
    nombre: "Producto popular 2",
    descripcion: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio ullam, quod laboru deserunt ratione",
    categoria: "Electrónica",
    marca: "Marca B",
    precio: 200,
    rating: 4.5,
    stock: 3,
    imagen: images.imagen2,
  },
  {
    id: 17,
    slug: "juguete-popular-3",
    nombre: "Juguete popular 3",
    descripcion: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio ullam, quod laborum deserunt plac",
    categoria: "Hogar",
    marca: "Marca C",
    precio: 300,
    rating: 4.5,
    stock: 5,
    imagen: images.imagen3,
  },
  {
    id: 18,
    slug: "producto-popular-4",
    nombre: "Producto popular 4",
    descripcion: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio, placeat ratione",
    categoria: "Deportes",
    marca: "Marca D",
    precio: 400,
    rating: 4.5,
    stock: 15,
    imagen: images.imagen4,
  },
  {
    id: 19,
    slug: "ropa-popular-5",
    nombre: "Ropa popular 5",
    descripcion: "Lorem ipsum dolor sit amet consec elit. Distinctio ullam, quod laborum deserunt placeat ratione",
    categoria: "Belleza",
    marca: "Marca E",
    precio: 500,
    rating: 4.5,
    stock: 17,
    imagen: images.imagen5,
  },
  {
    id: 20,
    slug: "producto-juguete",
    nombre: "Producto juguete",
    descripcion: "Lorem ipsum dolor adipisicing elit. Distinctio ullam, quod laborum deserunt placeat ratione maxime",
    categoria: "Juguetes",
    marca: "Marca F",
    precio: 100,
    rating: 4.5,
    stock: 14,
    imagen: images.imagen6,
  },
  {
    id: 21,
    slug: "jardinero-experto",
    nombre: "Jardinero experto",
    descripcion: "sectetur adipisicing elit. Distinctio ullam, quod laborum deserunt placeat ratione maxime",
    categoria: "Jardinería",
    marca: "Marca G",
    precio: 100,
    rating: 4.5,
    stock: 20,
    imagen: images.imagen7,
  },
  {
    id: 22,
    slug: "producto-tecnologico",
    nombre: "Producto tecnológico",
    descripcion: "tetur adipisicing elit. Distinctio ullam, quod laborum deserunt placeat ratione maxime",
    categoria: "Tecnología",
    marca: "Marca H",
    precio: 100,
    rating: 4.5,
    stock: 18,
    imagen: images.imagen8,
  },
  {
    id: 23,
    slug: "libro-popular-9",
    nombre: "Libro popular 9",
    descripcion: "Lorem ipsum Distinctio ullam, quod laborum deserunt placeat ratione maxime",
    categoria: "Libros",
    marca: "Marca I",
    precio: 100,
    rating: 4.5,
    stock: 40,
    imagen: images.imagen9,
  },
  {
    id: 24,
    slug: "producto-mascotas",
    nombre: "Producto para mascotas",
    descripcion: "dipisicing elit. Distinctio ullam, quod laborum deserunt placeat ratione maxime",
    categoria: "Mascotas",
    marca: "Marca J",
    precio: 100,
    rating: 4.5,
    stock: 46,
    imagen: images.imagen10,
  },
  {
    id: 25,
    slug: "producto-popular-11",
    nombre: "Producto popular 11",
    descripcion: "dipisicing elit. Distinctio ullam, quod laborum deserunt placeat ratione maxime",
    categoria: "Tecnología",
    marca: "Marca J",
    precio: 100,
    rating: 4.5,
    stock: 46,
    imagen: images.imagen10,  
  }
];

export default productsPopularData;
